;;;; Ex 1.9

;;; So, we have two procedures defining a method for adding two positive
;;;   integers using an `inc` procedure (add 1), and `dec` (subtract 1)
(define (inc x)
  (+ x 1))

(define (dec x)
  (- x 1))

(define (add a b)
  (if (= a 0)
      b
      (inc (add (dec a) b))))

(define (add a b)
  (if (= a 0)
      b
      (add (dec a) (inc b))))

;;; The goal is to describe the process generated by each of these
;;;   definitions, and then decide if the _processes_ are iterative or 
;;;   recursive

;;; definition 1 behavior:
(add 4 5)
(inc (add 3 5))
(inc (inc (add 2 5)))
(inc (inc (inc (add 1 5))))
(inc (inc (inc (inc (add 0 5)))))
(inc (inc (inc (inc 5))))
(inc (inc (inc 6)))
(inc (inc 7))
(inc 8)
9
;;; so, definition 1 generates a recursive process that expands & contracts

;;; definition 2 behavior:
(add 4 5)
(add 3 6)
(add 2 7)
(add 1 8)
(add 0 9)
9
;;; so, definition 2 generates an interative process, even though it is
;;;   a recursive procedure

